from datetime import datetime
from fpdf import FPDF
from .types import TalentReport

# Brand colors (same palette as linkedin_analyzer)
C_BLACK = (28, 28, 30)
C_WHITE = (240, 237, 230)
C_CREAM = (212, 207, 196)
C_RED = (192, 57, 43)
C_BORDER = (46, 46, 48)
C_MUTED = (85, 85, 85)
C_DARK_BG = (40, 40, 42)
C_ACCENT = (230, 160, 50)


def sanitize_pdf_text(text: str) -> str:
    replacements = {
        "\u2019": "'", "\u2018": "'", "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "--", "\u2026": "...", "\u00b7": "-",
        "\u00e9": "e", "\u00e8": "e", "\u00ea": "e", "\u00e0": "a",
        "\u00e2": "a", "\u00f4": "o", "\u00fb": "u", "\u00ee": "i",
        "\u00fc": "u", "\u00f6": "o", "\u00e4": "a",
    }
    for orig, repl in replacements.items():
        text = text.replace(orig, repl)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def truncate(text: str, length: int = 80) -> str:
    text = text or ""
    return text[:length] + "..." if len(text) > length else text


class TalentPDF(FPDF):
    def __init__(self):
        super().__init__(format="A4")
        self.set_auto_page_break(auto=True, margin=15)
        self.set_font("Helvetica", size=10)
        self._bg_color = None

    def set_background_color(self, color):
        self._bg_color = color
        if self.page_no() > 0:
            self.set_fill_color(*color)
            self.rect(0, 0, self.w, self.h, "F")

    def add_page(self, *args, **kwargs):
        super().add_page(*args, **kwargs)
        if self._bg_color:
            self.set_fill_color(*self._bg_color)
            self.rect(0, 0, self.w, self.h, "F")

    def header(self):
        pass

    def footer(self):
        if self.page_no() > 1:
            self.set_y(-15)
            self.set_draw_color(*C_MUTED)
            self.set_line_width(0.2)
            self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
            self.set_y(-12)
            self.set_font("Helvetica", size=8)
            self.set_text_color(*C_MUTED)
            self.cell(0, 5, "Generated by Behram Shukur", 0, 0, "L")

    def add_section_label(self, label: str):
        self.ln(5)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*C_RED)
        self.cell(0, 8, sanitize_pdf_text(" ".join(label.upper())), ln=1)

    def add_section_title(self, title: str):
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(*C_WHITE)
        self.cell(0, 10, sanitize_pdf_text(title.upper()), ln=1)
        self.ln(5)

    def add_metric_row(self, label: str, value: str):
        self.set_font("Helvetica", size=10)
        start_y = self.get_y()
        self.set_draw_color(*C_BORDER)
        self.line(self.l_margin, start_y + 8, self.w - self.r_margin, start_y + 8)
        self.set_text_color(*C_CREAM)
        self.cell(110, 8, sanitize_pdf_text(label))
        self.set_text_color(*C_WHITE)
        self.cell(0, 8, sanitize_pdf_text(value), align="R", ln=1)
        self.ln(2)

    def add_body_text(self, text: str, color=None):
        color = color or C_CREAM
        self.set_font("Helvetica", size=10)
        self.set_text_color(*color)
        self.multi_cell(0, 6, sanitize_pdf_text(text))
        self.ln(3)

    def add_candidate_card(self, rank: int, name: str, title: str, location: str,
                           profile_url: str, why: str, angle: str):
        """A ranked candidate card with rank badge, details, and outreach angle."""
        card_x = self.l_margin
        card_w = self.w - self.l_margin - self.r_margin
        card_y = self.get_y()

        # Estimate height
        why_lines = max(1, len(why) // 70 + 1)
        angle_lines = max(1, len(angle) // 70 + 1)
        card_h = 10 + 8 + (why_lines * 6) + 4 + (angle_lines * 6) + 10

        if card_y + card_h > self.h - 25:
            self.add_page()
            card_y = self.get_y()

        # Background
        self.set_fill_color(*C_DARK_BG)
        self.rect(card_x, card_y, card_w, card_h, "F")

        # Rank badge
        self.set_xy(card_x + 3, card_y + 3)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*C_ACCENT)
        self.cell(12, 8, f"#{rank}", ln=0)

        # Name + title
        self.set_x(card_x + 17)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*C_WHITE)
        self.cell(card_w - 20, 6, sanitize_pdf_text(truncate(name, 50)), ln=1)

        self.set_x(card_x + 17)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(*C_CREAM)
        loc_title = f"{truncate(title, 40)}  |  {location}" if location else truncate(title, 50)
        self.cell(card_w - 20, 5, sanitize_pdf_text(loc_title), ln=1)

        self.ln(2)

        # Why target
        self.set_x(card_x + 4)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*C_RED)
        self.cell(30, 5, "WHY TARGET", ln=0)
        self.set_font("Helvetica", size=9)
        self.set_text_color(*C_CREAM)
        self.set_x(card_x + 4)
        self.ln(5)
        self.set_x(card_x + 4)
        self.multi_cell(card_w - 8, 5, sanitize_pdf_text(why))

        # Outreach angle
        self.set_x(card_x + 4)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*C_ACCENT)
        self.cell(40, 5, "OUTREACH ANGLE", ln=0)
        self.set_font("Helvetica", size=9)
        self.set_text_color(*C_WHITE)
        self.ln(5)
        self.set_x(card_x + 4)
        self.multi_cell(card_w - 8, 5, sanitize_pdf_text(angle))

        self.ln(4)

    def add_dm_card(self, number: int, name: str, subject: str, message: str, profile_url: str):
        """A DM draft card."""
        card_x = self.l_margin
        card_w = self.w - self.l_margin - self.r_margin
        card_y = self.get_y()

        msg_lines = max(1, len(message) // 80 + 1)
        card_h = 8 + 8 + (msg_lines * 6) + 8

        if card_y + card_h > self.h - 25:
            self.add_page()
            card_y = self.get_y()

        self.set_fill_color(*C_DARK_BG)
        self.rect(card_x, card_y, card_w, card_h, "F")

        self.set_xy(card_x + 4, card_y + 4)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*C_ACCENT)
        self.cell(20, 5, f"DM {number}", ln=0)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*C_WHITE)
        self.cell(0, 5, sanitize_pdf_text(f"{name} — {subject}"), ln=1)

        self.set_x(card_x + 4)
        self.set_font("Helvetica", size=9)
        self.set_text_color(*C_CREAM)
        self.multi_cell(card_w - 8, 5, sanitize_pdf_text(message))

        self.set_x(card_x + 4)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*C_MUTED)
        self.cell(0, 5, sanitize_pdf_text(truncate(profile_url, 70)), ln=1)

        self.ln(4)

    def add_insight_card(self, number: int, observation: str, pattern: str, implication: str):
        """A team structure insight card."""
        card_x = self.l_margin
        card_w = self.w - self.l_margin - self.r_margin
        card_y = self.get_y()

        obs_lines = max(1, len(observation) // 75 + 1)
        pat_lines = max(1, len(pattern) // 75 + 1)
        imp_lines = max(1, len(implication) // 75 + 1)
        card_h = 8 + (obs_lines * 5) + (pat_lines * 5) + (imp_lines * 5) + 14

        if card_y + card_h > self.h - 25:
            self.add_page()
            card_y = self.get_y()

        self.set_fill_color(*C_DARK_BG)
        self.rect(card_x, card_y, card_w, card_h, "F")

        self.set_xy(card_x + 4, card_y + 4)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*C_ACCENT)
        self.cell(12, 6, f"{number}.", ln=0)

        self.ln(6)

        for label, text, color in [
            ("OBSERVATION", observation, C_CREAM),
            ("PATTERN", pattern, C_WHITE),
            ("IMPLICATION", implication, C_ACCENT),
        ]:
            self.set_x(card_x + 4)
            self.set_font("Helvetica", "B", 8)
            self.set_text_color(*C_RED)
            self.cell(0, 4, label, ln=1)
            self.set_x(card_x + 4)
            self.set_font("Helvetica", size=9)
            self.set_text_color(*color)
            self.multi_cell(card_w - 8, 5, sanitize_pdf_text(text))
            self.ln(1)

        self.ln(4)


# ============================================================
# MAIN GENERATOR
# ============================================================


def generate_talent_pdf(report: TalentReport) -> bytes:
    pdf = TalentPDF()
    pdf.set_background_color(C_BLACK)

    # ── PAGE 1: COVER ──────────────────────────────────────────
    pdf.add_page()

    pdf.set_xy(pdf.l_margin, 50)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*C_RED)
    pdf.cell(0, 8, "T A L E N T   S C O U T   R E P O R T", ln=1)
    pdf.ln(4)

    # Company name from URL
    company_name = report.companyUrl.rstrip("/").split("/")[-1].replace("-", " ").title()

    pdf.set_font("Helvetica", "B", 32)
    pdf.set_text_color(*C_WHITE)
    pdf.multi_cell(0, 14, sanitize_pdf_text(company_name.upper()))
    pdf.ln(4)

    pdf.set_font("Helvetica", size=14)
    pdf.set_text_color(*C_CREAM)
    pdf.cell(0, 8, sanitize_pdf_text(f'Target Role: "{report.targetTitle}"'), ln=1)
    pdf.ln(2)

    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(0, 7, f"{report.totalCandidatesFound} matching profiles found", ln=1)
    pdf.ln(2)

    scouted_date = report.scoutedAt[:10] if report.scoutedAt else datetime.utcnow().strftime("%Y-%m-%d")
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(0, 7, f"Scouted: {scouted_date}", ln=1)

    # Divider
    pdf.set_y(pdf.h - 50)
    pdf.set_draw_color(*C_RED)
    pdf.set_line_width(0.8)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(0, 6, "CONFIDENTIAL — For internal use only", ln=1)

    # ── PAGE 2: EXECUTIVE SUMMARY ─────────────────────────────
    pdf.add_page()

    pdf.set_xy(pdf.l_margin, 20)
    pdf.add_section_label("Intelligence Brief")
    pdf.add_section_title("Executive Summary")

    if report.executiveSummary:
        pdf.add_body_text(report.executiveSummary, color=C_WHITE)
    pdf.ln(4)

    # Quick stats
    pdf.add_metric_row("Company Scouted", sanitize_pdf_text(company_name))
    pdf.add_metric_row("Target Title Filter", sanitize_pdf_text(report.targetTitle))
    pdf.add_metric_row("Total Matched Profiles", str(report.totalCandidatesFound))
    pdf.add_metric_row("Top Targets Identified", str(len(report.top5)))
    pdf.add_metric_row("Outreach Drafts Generated", str(len(report.outreachDrafts)))

    # ── PAGE 3: TOP 5 TARGETS ─────────────────────────────────
    pdf.add_page()

    pdf.set_xy(pdf.l_margin, 20)
    pdf.add_section_label("Priority Targets")
    pdf.add_section_title("Top 5 Candidates")

    if report.top5:
        for candidate in report.top5:
            pdf.add_candidate_card(
                rank=candidate.rank,
                name=candidate.name,
                title=candidate.title,
                location=candidate.location,
                profile_url=candidate.profileUrl,
                why=candidate.whyTarget,
                angle=candidate.outreachAngle,
            )
    else:
        pdf.add_body_text("No AI ranking available (run without --skip-ai).")

    # ── PAGE 4: OUTREACH DRAFTS ───────────────────────────────
    pdf.add_page()

    pdf.set_xy(pdf.l_margin, 20)
    pdf.add_section_label("Ready-to-Send Messages")
    pdf.add_section_title("Outreach Drafts")

    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(0, 6, "Copy, personalize, and send via LinkedIn InMail or Connection Request.", ln=1)
    pdf.ln(4)

    if report.outreachDrafts:
        for i, draft in enumerate(report.outreachDrafts, 1):
            pdf.add_dm_card(
                number=i,
                name=draft.candidateName,
                subject=draft.subject,
                message=draft.message,
                profile_url=draft.profileUrl,
            )
    else:
        pdf.add_body_text("No outreach drafts available (run without --skip-ai).")

    # ── PAGE 5: TEAM STRUCTURE INSIGHTS ───────────────────────
    pdf.add_page()

    pdf.set_xy(pdf.l_margin, 20)
    pdf.add_section_label("Competitive Intelligence")
    pdf.add_section_title("Team Structure Insights")

    if report.teamInsights:
        for i, insight in enumerate(report.teamInsights, 1):
            pdf.add_insight_card(
                number=i,
                observation=insight.observation,
                pattern=insight.pattern,
                implication=insight.implication,
            )
    else:
        pdf.add_body_text("No team insights available (run without --skip-ai).")

    # ── PAGE 6: FULL CANDIDATE LIST ───────────────────────────
    pdf.add_page()

    pdf.set_xy(pdf.l_margin, 20)
    pdf.add_section_label("Complete Dataset")
    pdf.add_section_title("All Matched Candidates")

    pdf.set_font("Helvetica", size=8)
    display_limit = min(len(report.candidates), 60)
    for i, c in enumerate(report.candidates[:display_limit], 1):
        pdf.set_text_color(*C_CREAM)
        pdf.set_x(pdf.l_margin)
        line = f"{i:3}.  {c.name:<28}  {truncate(c.title, 35):<35}  {c.location}"
        pdf.cell(0, 5, sanitize_pdf_text(line), ln=1)
        if i % 2 == 0:
            # subtle alternating separator
            pdf.set_draw_color(*C_BORDER)
            pdf.set_line_width(0.1)

    if len(report.candidates) > display_limit:
        pdf.ln(4)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*C_MUTED)
        remaining = len(report.candidates) - display_limit
        pdf.cell(0, 6, f"... and {remaining} more candidates in the exported JSON.", ln=1)

    return bytes(pdf.output())
