from datetime import datetime
from fpdf import FPDF
from .types import FullAnalysis, PostDeconstruction

# Brand colors
C_BLACK = (28, 28, 30)
C_WHITE = (240, 237, 230)
C_CREAM = (212, 207, 196)
C_RED = (192, 57, 43)
C_BORDER = (46, 46, 48)
C_MUTED = (85, 85, 85)
C_DARK_BG = (40, 40, 42)
C_POST_BG = (240, 237, 230)
C_POST_TXT = (28, 28, 30)
C_ACCENT = (230, 160, 50)  # gold accent for "steal this" hooks


class ReportPDF(FPDF):
    def __init__(self):
        super().__init__(format="A4")
        self.set_auto_page_break(auto=True, margin=15)
        self.set_font("Helvetica", size=10)
        self._bg_color = None

    def set_background_color(self, color):
        self._bg_color = color
        if self.page_no() > 0:
            self.set_fill_color(*color)
            self.rect(0, 0, self.w, self.h, "F")

    def add_page(self, *args, **kwargs):
        super().add_page(*args, **kwargs)
        if self._bg_color:
            self.set_fill_color(*self._bg_color)
            self.rect(0, 0, self.w, self.h, "F")

    def header(self):
        pass

    def footer(self):
        if self.page_no() > 1:
            self.set_y(-15)
            self.set_draw_color(*C_MUTED)
            self.set_line_width(0.2)
            self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
            self.set_y(-12)
            self.set_font("Helvetica", size=8)
            self.set_text_color(*C_MUTED)
            self.cell(0, 5, "Generated by Behram Shukur", 0, 0, "L")

    def add_section_label(self, label: str):
        self.ln(5)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*C_RED)
        spaced_label = " ".join(label.upper())
        self.cell(0, 8, sanitize_pdf_text(spaced_label), ln=1)

    def add_section_title(self, title: str):
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(*C_WHITE)
        self.cell(0, 10, sanitize_pdf_text(title.upper()), ln=1)
        self.ln(5)

    def add_metric_row(self, label: str, value: str):
        self.set_font("Helvetica", size=10)
        start_y = self.get_y()
        self.set_draw_color(*C_BORDER)
        self.line(self.l_margin, start_y + 8, self.w - self.r_margin, start_y + 8)
        self.set_text_color(*C_CREAM)
        self.cell(100, 8, sanitize_pdf_text(label))
        self.set_text_color(*C_WHITE)
        self.cell(0, 8, sanitize_pdf_text(value), align="R", ln=1)
        self.ln(2)

    def add_stat_card_row(self, cards):
        width = (self.w - self.l_margin - self.r_margin - 20) / 3
        start_x = self.get_x()
        start_y = self.get_y()
        max_y = start_y

        for i, card in enumerate(cards):
            x = start_x + (i % 3) * (width + 10)
            if i > 0 and i % 3 == 0:
                start_y = max_y + 10
                x = start_x

            self.set_xy(x, start_y)
            self.set_fill_color(*C_DARK_BG)
            self.set_draw_color(*C_BORDER)
            self.rect(x, start_y, width, 25, "DF")

            self.set_xy(x + 5, start_y + 3)
            self.set_font("Helvetica", size=8)
            self.set_text_color(180, 180, 180)
            self.cell(width - 10, 5, card["label"])

            self.set_xy(x + 5, start_y + 8)
            self.set_font("Helvetica", "B", 14)
            self.set_text_color(*C_WHITE)
            self.cell(width - 10, 8, card["value"])

            if "sub" in card and card["sub"]:
                self.set_xy(x + 5, start_y + 16)
                self.set_font("Helvetica", size=8)
                self.set_text_color(180, 180, 180)
                self.cell(width - 10, 5, card["sub"])

            max_y = max(max_y, start_y + 25)

        self.set_xy(self.l_margin, max_y + 5)

    def add_card(self, title: str, body: str, tag: str, tag_color=C_RED):
        self.set_fill_color(*C_DARK_BG)
        self.set_draw_color(*C_BORDER)

        start_y = self.get_y()

        self.set_font("Helvetica", size=9)
        safe_body = sanitize_pdf_text(body)
        num_lines = len(
            self.multi_cell(
                self.w - self.l_margin - self.r_margin - 10,
                5,
                safe_body,
                split_only=True,
            )
        )
        height = 10 + (num_lines * 5) + 10

        if start_y + height > self.page_break_trigger:
            self.add_page()
            start_y = self.get_y()

        self.rect(
            self.l_margin, start_y, self.w - self.l_margin - self.r_margin, height, "DF"
        )

        self.set_xy(self.l_margin + 5, start_y + 5)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*C_WHITE)
        self.cell(0, 5, sanitize_pdf_text(title), ln=1)

        self.set_xy(self.l_margin + 5, self.get_y() + 2)
        self.set_font("Helvetica", size=9)
        self.set_text_color(*C_CREAM)
        self.multi_cell(0, 5, safe_body)

        self.set_xy(self.l_margin + 5, self.get_y() + 2)
        self.set_font("Helvetica", size=8)
        self.set_text_color(*tag_color)
        self.cell(0, 5, sanitize_pdf_text(tag), ln=1)

        self.ln(5)

    def add_hook_card(self, number: int, hook: str, archetype: str, why: str):
        """Styled card for 'Steal This Hook' section."""
        self.set_fill_color(*C_DARK_BG)
        self.set_draw_color(*C_BORDER)

        start_y = self.get_y()
        safe_hook = sanitize_pdf_text(hook)
        safe_why = sanitize_pdf_text(why)

        hook_lines = len(
            self.multi_cell(
                self.w - self.l_margin - self.r_margin - 23,
                6,
                safe_hook,
                split_only=True,
            )
        )
        why_lines = len(
            self.multi_cell(
                self.w - self.l_margin - self.r_margin - 23,
                4,
                safe_why,
                split_only=True,
            )
        )
        height = 8 + (hook_lines * 6) + 5 + (why_lines * 4) + 8

        if start_y + height > self.page_break_trigger:
            self.add_page()
            start_y = self.get_y()

        self.rect(
            self.l_margin, start_y, self.w - self.l_margin - self.r_margin, height, "DF"
        )

        # Number badge
        self.set_xy(self.l_margin + 5, start_y + 5)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*C_ACCENT)
        self.cell(12, 8, str(number))

        # Hook text
        self.set_xy(self.l_margin + 18, start_y + 5)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*C_WHITE)
        self.multi_cell(self.w - self.l_margin - self.r_margin - 23, 6, safe_hook)

        # Archetype + why
        self.set_xy(self.l_margin + 18, self.get_y() + 1)
        self.set_font("Helvetica", size=8)
        self.set_text_color(*C_ACCENT)
        self.cell(0, 4, sanitize_pdf_text(f"[{archetype}]  "), ln=1)

        self.set_xy(self.l_margin + 18, self.get_y() + 1)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*C_MUTED)
        self.multi_cell(self.w - self.l_margin - self.r_margin - 23, 4, safe_why)

        self.set_y(start_y + height + 4)

    def add_agent_card(self, number: int, name: str, pillar: str, description: str, skeleton: str):
        """Styled card for AI-Native Blueprint workflows — 3 visual zones."""
        card_x = self.l_margin
        card_w = self.w - self.l_margin - self.r_margin
        inner_w = card_w - 20  # 10px padding each side
        pad_x = card_x + 10

        safe_desc = sanitize_pdf_text(description)
        safe_skeleton = sanitize_pdf_text(skeleton)

        # Pre-calculate line counts using inner_w
        self.set_font("Helvetica", size=9)
        desc_lines = len(self.multi_cell(inner_w, 5, safe_desc, split_only=True))
        self.set_font("Helvetica", "I", 8)
        skel_lines = len(self.multi_cell(inner_w, 5, safe_skeleton, split_only=True))

        HEADER_H = 22   # number + name + pillar tag
        BODY_H = 8 + (desc_lines * 5)
        SKEL_H = 10 + (skel_lines * 5) + 6
        total_h = HEADER_H + BODY_H + SKEL_H

        start_y = self.get_y()
        if start_y + total_h > self.page_break_trigger:
            self.add_page()
            start_y = self.get_y()

        # ── Zone 1: Header (darker bg) ──────────────────────────────────
        C_HEADER_BG = (33, 33, 35)
        self.set_fill_color(*C_HEADER_BG)
        self.set_draw_color(*C_BORDER)
        self.rect(card_x, start_y, card_w, HEADER_H, "DF")

        # Red left accent bar
        self.set_fill_color(*C_RED)
        self.rect(card_x, start_y, 3, total_h, "F")

        # Number badge
        self.set_xy(card_x + 8, start_y + 4)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*C_RED)
        self.cell(10, 7, f"{number}.")

        # Agent name
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*C_WHITE)
        self.cell(0, 7, sanitize_pdf_text(name), ln=1)

        # Pillar pill
        self.set_xy(card_x + 20, start_y + 13)
        self.set_font("Helvetica", size=8)
        self.set_text_color(*C_ACCENT)
        self.cell(0, 5, sanitize_pdf_text(f"Pillar: {pillar}"), ln=1)

        # ── Zone 2: Description body ─────────────────────────────────────
        body_y = start_y + HEADER_H
        self.set_fill_color(*C_DARK_BG)
        self.set_draw_color(*C_BORDER)
        self.rect(card_x, body_y, card_w, BODY_H, "DF")

        self.set_xy(pad_x, body_y + 4)
        self.set_font("Helvetica", size=9)
        self.set_text_color(*C_CREAM)
        self.multi_cell(inner_w, 5, safe_desc)

        # ── Zone 3: Skeleton footer (slightly darker tint) ───────────────
        skel_y = body_y + BODY_H
        C_SKEL_BG = (33, 33, 35)
        self.set_fill_color(*C_SKEL_BG)
        self.set_draw_color(*C_BORDER)
        self.rect(card_x, skel_y, card_w, SKEL_H, "DF")

        # Divider line between body and skeleton
        self.set_draw_color(*C_RED)
        self.set_line_width(0.3)
        self.line(card_x + 3, skel_y, card_x + card_w, skel_y)
        self.set_line_width(0.2)
        self.set_draw_color(*C_BORDER)

        self.set_xy(pad_x, skel_y + 3)
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*C_RED)
        self.cell(0, 4, "STARTER PROMPT SKELETON:", ln=1)

        self.set_xy(pad_x, self.get_y() + 1)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.multi_cell(inner_w, 5, safe_skeleton)

        self.set_y(start_y + total_h + 5)

    def add_post_card(self, text: str):
        self.set_fill_color(*C_POST_BG)
        self.set_font("Helvetica", size=9)
        safe_text = sanitize_pdf_text(text)
        num_lines = len(
            self.multi_cell(
                self.w - self.l_margin - self.r_margin - 10,
                5,
                safe_text,
                split_only=True,
            )
        )
        height = 10 + (num_lines * 5)

        start_y = self.get_y()
        if start_y + height > self.page_break_trigger:
            self.add_page()
            start_y = self.get_y()

        self.rect(
            self.l_margin, start_y, self.w - self.l_margin - self.r_margin, height, "F"
        )

        self.set_xy(self.l_margin + 5, start_y + 5)
        self.set_text_color(*C_POST_TXT)
        self.multi_cell(0, 5, safe_text)
        self.ln(5)

    def add_opportunity_banner(self, text: str):
        """Full-width banner for 'Big Strategic Opportunity'."""
        self.set_fill_color(*C_RED)
        safe_text = sanitize_pdf_text(text)
        self.set_font("Helvetica", size=9)
        num_lines = len(
            self.multi_cell(
                self.w - self.l_margin - self.r_margin - 10,
                5,
                safe_text,
                split_only=True,
            )
        )
        height = 10 + (num_lines * 5) + 6

        start_y = self.get_y()
        if start_y + height > self.page_break_trigger:
            self.add_page()
            start_y = self.get_y()

        self.rect(
            self.l_margin, start_y, self.w - self.l_margin - self.r_margin, height, "F"
        )

        self.set_xy(self.l_margin + 5, start_y + 5)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*C_WHITE)
        self.cell(0, 5, "THE BIG STRATEGIC OPPORTUNITY", ln=1)

        self.set_xy(self.l_margin + 5, self.get_y() + 2)
        self.set_font("Helvetica", size=9)
        self.multi_cell(self.w - self.l_margin - self.r_margin - 10, 5, safe_text)

        self.set_y(start_y + height + 6)


def truncate(text: str, length: int) -> str:
    if len(text) > length:
        return text[:length] + "..."
    return text


def sanitize_pdf_text(text: str) -> str:
    if text is None:
        return ""
    replacements = {
        "\u2022": "-",
        "\u2013": "-",
        "\u2014": "-",
        "\u201c": '"',
        "\u201d": '"',
        "\u2018": "'",
        "\u2019": "'",
        "\u2026": "...",
        "\u00a0": " ",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", "replace").decode("latin-1")


def post_title(text: str, fallback: str, length: int = 80) -> str:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    title = lines[0] if lines else fallback
    return truncate(title, length)


def add_post_list(pdf: ReportPDF, label: str, posts: list):
    pdf.add_section_label(label)
    if not posts:
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(0, 6, "No posts available.", ln=1)
        pdf.ln(2)
        return

    for i, p in enumerate(posts, 1):
        rank_hint = getattr(p, "ageAdjustedRank", 0) or getattr(p, "rank", 0) or i
        title = post_title(p.text, f"Post #{rank_hint}")
        link = getattr(p, "url", "") or ""

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*C_CREAM)
        if link:
            pdf.cell(0, 6, sanitize_pdf_text(f"{i}. {title}"), ln=1, link=link)
        else:
            pdf.cell(0, 6, sanitize_pdf_text(f"{i}. {title}"), ln=1)

        pdf.set_font("Helvetica", size=8)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(
            0,
            5,
            sanitize_pdf_text(
                f"{p.numLikes} likes  {p.numComments} comments  {p.numShares} reposts"
            ),
            ln=1,
        )
    pdf.ln(2)


def generate_pdf(a: FullAnalysis, include_cta: bool = True) -> bytes:
    pdf = ReportPDF()

    def set_bg():
        pdf.set_background_color(C_BLACK)

    pdf.add_page()
    set_bg()

    # =========================================================
    # PAGE 1: COVER — Title + Profile
    # =========================================================
    pdf.set_y(pdf.h / 2 - 50)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*C_RED)
    pdf.cell(0, 10, "L I N K E D I N   S T R A T E G Y   A N A L Y S I S", align="C", ln=1)

    pdf.set_font("Helvetica", "B", 30)
    pdf.set_text_color(*C_WHITE)
    pdf.cell(0, 15, sanitize_pdf_text(a.profileName.upper()), align="C", ln=1)

    pdf.set_font("Helvetica", size=12)
    pdf.set_text_color(*C_CREAM)
    pdf.cell(0, 8, sanitize_pdf_text(a.profileHeadline), align="C", ln=1)

    date_str = (
        datetime.fromisoformat(a.analyzedAt.replace("Z", "+00:00")).strftime("%B %d, %Y")
        if a.analyzedAt
        else "Today"
    )
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(0, 20, sanitize_pdf_text(f"Report generated {date_str}"), align="C", ln=1)

    pdf.ln(8)
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(
        0,
        10,
        sanitize_pdf_text(
            f"{a.cadence.totalPosts} posts analyzed  |  {a.cadence.periodStart} to {a.cadence.periodEnd}"
        ),
        align="C",
        ln=1,
    )

    # =========================================================
    # PAGE 2: EXECUTIVE SUMMARY + BIG STRATEGIC OPPORTUNITY
    # =========================================================
    pdf.add_page()
    pdf.add_section_label("SECTION 1")
    pdf.add_section_title("The Strategic Picture")

    # Key performance stats at a glance
    pdf.add_stat_card_row(
        [
            {
                "label": "AVG REACTIONS",
                "value": str(a.engagement.avgReactions),
                "sub": f"median: {a.engagement.medianReactions}",
            },
            {
                "label": "AVG COMMENTS",
                "value": str(a.engagement.avgComments),
                "sub": f"median: {a.engagement.medianComments}",
            },
            {
                "label": "POSTING PACE",
                "value": f"{a.cadence.postsPerWeek}/wk",
                "sub": f"every {a.cadence.avgDaysBetweenPosts} days",
            },
        ]
    )

    pdf.add_section_label("EXECUTIVE SUMMARY")
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_CREAM)
    pdf.multi_cell(0, 6, sanitize_pdf_text(a.executiveSummary))
    pdf.ln(4)

    if a.bigStrategicOpportunity:
        pdf.add_opportunity_banner(a.bigStrategicOpportunity)

    # Top 5 + Worst 3 (truncated — no fluff)
    add_post_list(pdf, "TOP 5 POSTS (AGE-ADJUSTED SCORE)", a.topPosts[:5])
    add_post_list(pdf, "WORST 3 POSTS (WHAT TO AVOID)", a.worstPosts[:3])

    # =========================================================
    # PAGE 3: TOP 3 CONTENT PILLARS — DEEP DIVE
    # =========================================================
    pdf.add_page()
    pdf.add_section_label("SECTION 2")
    pdf.add_section_title("Content Pillars — Deep Dive")

    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(
        0, 6,
        "These are not just topics. They are the strategic positions this creator owns in the feed.",
        ln=1,
    )
    pdf.ln(4)

    for p in a.contentPillars[:3]:
        pdf.add_card(
            p.name,
            p.description,
            f"~{p.percentageOfPosts}% of posts  |  {p.engagementLevel} engagement",
        )

    pdf.add_section_label("POST ARCHETYPES")
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(
        0, 6,
        "The formats that do the heavy lifting — how the pillars are packaged for the feed.",
        ln=1,
    )
    pdf.ln(2)

    for ar in a.postArchetypes:
        pdf.add_card(
            ar.name,
            ar.description,
            f"{ar.count} posts  |  {ar.engagementLevel} engagement",
        )

    # =========================================================
    # PAGE 4: AI-NATIVE BLUEPRINT
    # =========================================================
    pdf.add_page()
    pdf.add_section_label("SECTION 3")
    pdf.add_section_title("The AI-Native Blueprint")

    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_CREAM)
    pdf.multi_cell(
        0, 6,
        sanitize_pdf_text(
            "A solo operator with the right AI agents can produce this creator's entire "
            "content output in a fraction of the time. Here are 3 specific agent workflows "
            "mapped directly to their top pillars."
        ),
    )
    pdf.ln(6)

    if a.agentWorkflows:
        for i, wf in enumerate(a.agentWorkflows, 1):
            pdf.add_agent_card(i, wf.name, wf.pillar, wf.description, wf.prompt_skeleton)
    else:
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(0, 6, "Agent workflows not available (AI skipped or analysis failed).", ln=1)

    # =========================================================
    # PAGE 5: STEAL THESE HOOKS
    # =========================================================
    pdf.add_page()
    pdf.add_section_label("SECTION 4")
    pdf.add_section_title("Steal These Hooks")

    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_CREAM)
    pdf.multi_cell(
        0, 6,
        sanitize_pdf_text(
            "5 ready-to-publish hooks modeled on this creator's best-performing archetypes. "
            "Copy, adapt the context, post."
        ),
    )
    pdf.ln(6)

    if a.stealTheseHooks:
        for i, h in enumerate(a.stealTheseHooks, 1):
            pdf.add_hook_card(i, h.hook, h.archetype, h.why_it_works)
    else:
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(0, 6, "Hooks not available (AI skipped or analysis failed).", ln=1)

    pdf.ln(6)

    # Hook formula callout
    if a.hookStrategy.formula and a.hookStrategy.formula not in ("AI skipped", "Analysis unavailable"):
        pdf.add_card(
            "WINNING HOOK FORMULA",
            a.hookStrategy.formula,
            "",
            tag_color=C_RED,
        )

    # =========================================================
    # PAGE 6+: REFERENCE DATA
    # =========================================================
    pdf.add_page()
    pdf.add_section_label("REFERENCE DATA")
    pdf.add_section_title("Raw Metrics")

    pdf.add_section_label("CONTENT CADENCE")
    pdf.add_metric_row("Posts Analyzed", str(a.cadence.totalPosts))
    pdf.add_metric_row("Time Period", f"{a.cadence.periodStart} -> {a.cadence.periodEnd}")
    pdf.add_metric_row("Weeks Covered", str(a.cadence.weeksCovered))
    pdf.add_metric_row("Total Reactions", f"{a.engagement.totalReactions:,}")
    pdf.add_metric_row("Total Comments", f"{a.engagement.totalComments:,}")

    pdf.add_section_label("POST TYPE BREAKDOWN")
    for pt in a.postTypes:
        pdf.add_metric_row(
            f"{pt.type.upper()} ({pt.percentage}%)",
            f"{pt.count} posts  avg {pt.avgReactions} reactions",
        )

    pdf.add_section_label("TEXT PATTERNS")
    pdf.add_metric_row("Avg Word Count", str(a.textPatterns.avgWordCount))
    pdf.add_metric_row(
        "Posts with CTA", f"{a.textPatterns.postsWithCTA}/{a.cadence.totalPosts}"
    )
    lift_sign = "+" if a.textPatterns.ctaEngagementLift > 0 else ""
    pdf.add_metric_row(
        "CTA Engagement Lift", f"{lift_sign}{a.textPatterns.ctaEngagementLift}%"
    )
    pdf.add_metric_row(
        "Posts with Hook", f"{a.textPatterns.postsWithHook}/{a.cadence.totalPosts}"
    )
    pdf.add_metric_row(
        "Posts with Questions",
        f"{a.textPatterns.postsWithQuestions}/{a.cadence.totalPosts}",
    )

    pdf.add_section_label("HOOK ANALYSIS")
    h = a.hookAnalysis
    pdf.add_metric_row("Avg Hook Length", f"{h.avgHookLength} words")
    pdf.add_metric_row("Urgency Rate", f"{h.urgencyRate}% of posts")
    top_hook_type = h.hookTypes[0] if h.hookTypes else None
    pdf.add_metric_row(
        "Top Hook Type",
        f"{top_hook_type.type if top_hook_type else 'N/A'} ({top_hook_type.percentage if top_hook_type else 0}%)",
    )
    pdf.add_metric_row("Top First Words", ", ".join(w.word for w in h.topFirstWords[:5]))

    pdf.add_section_label("CTA ANALYSIS")
    cta = a.ctaAnalysis
    pdf.add_metric_row("No CTA Rate", f"{cta.noCTARate}% of posts")
    pdf.add_metric_row("Best CTA Type", cta.bestCTAType)
    pdf.add_metric_row("Top Action Words", ", ".join(w.word for w in cta.topActionWords[:5]))

    pdf.add_section_label("TOP 25 WORDS (NLP FREQUENCY)")
    pdf.set_font("Helvetica", size=9)
    col_w = (pdf.w - pdf.l_margin - pdf.r_margin - 10) / 2
    y_start = pdf.get_y()

    for i, wf in enumerate(a.wordFrequency):
        col = 0 if i % 2 == 0 else 1
        row = i // 2

        x = pdf.l_margin + col * (col_w + 10)
        y = y_start + row * 8

        pdf.set_xy(x, y)
        pdf.set_draw_color(*C_BORDER)
        pdf.line(x, y + 6, x + col_w, y + 6)

        pdf.set_text_color(*C_CREAM)
        pdf.cell(col_w - 20, 6, f"{i+1}. {wf.word}")

        pdf.set_text_color(*C_WHITE)
        pdf.cell(20, 6, str(wf.count), align="R")

    pdf.set_y(pdf.get_y() + 10)

    # =========================================================
    # FINAL PAGE: OFFER / CTA
    # =========================================================
    if include_cta:
        _add_cta_page(pdf)

    return bytes(pdf.output(dest="S"))


def _add_cta_page(pdf: ReportPDF):
    """Shared CTA / offer page — reused by both report types."""
    pdf.add_page()
    pdf.set_y(pdf.h / 2 - 75)

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*C_RED)
    pdf.cell(0, 10, "W H A T ' S   N E X T ?", align="C", ln=1)

    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*C_WHITE)
    pdf.cell(0, 14, "BUILD YOUR AI-NATIVE CONTENT ENGINE", align="C", ln=1)

    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*C_RED)
    pdf.cell(0, 7, "THE REALITY CHECK", align="C", ln=1)
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_CREAM)
    pdf.set_x(pdf.w / 2 - 75)
    pdf.multi_cell(150, 5, sanitize_pdf_text(
        "Analyzing the data is the first step. Operating with the leverage of a 10-person team is the transformation. "
        "Most solo operators spend 10+ hours a week manually drafting, editing, and guessing what works. "
        "You don't have to."
    ), align="C")

    pdf.ln(5)

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*C_RED)
    pdf.cell(0, 7, "THE SOLUTION", align="C", ln=1)
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_CREAM)
    pdf.set_x(pdf.w / 2 - 75)
    pdf.multi_cell(150, 5, sanitize_pdf_text(
        "I help solo founders build the exact AI Agent systems found in this report. "
        "We automate your research, hook generation, and content pillars -- "
        "so you can spend your time on sales and building, not scrolling."
    ), align="C")

    pdf.ln(5)

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*C_RED)
    pdf.cell(0, 7, "THE 30-DAY SPRINT", align="C", ln=1)
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_CREAM)
    pdf.set_x(pdf.w / 2 - 75)
    pdf.multi_cell(150, 5, sanitize_pdf_text(
        "I'm taking on 3 solo operators this month for a 1-v-1 high-ticket transformation.\n"
        "  AUDIT: A deep-dive into your specific niche.\n"
        "  BUILD: We'll build the agents to automate your strategy.\n"
        "  SCALE: Launch your AI-native content engine in 30 days."
    ), align="C")

    pdf.ln(8)

    pdf.set_fill_color(*C_RED)
    pdf.set_text_color(*C_WHITE)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_x(pdf.w / 2 - 70)
    pdf.cell(140, 14, "Book your 1-v-1 Strategy Audit ->  cal.com/behram-antifragile/30min", fill=True, align="C", ln=1, link="https://cal.com/behram-antifragile/30min")


def generate_post_pdf(d: PostDeconstruction, include_cta: bool = True) -> bytes:
    """Generate a 2-page PDF for a single post deconstruction + CTA page."""
    pdf = ReportPDF()
    pdf.set_background_color(C_BLACK)

    # =========================================================
    # PAGE 1: Post Deconstruction
    # =========================================================
    pdf.add_page()
    pdf.set_y(18)

    # Header label
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*C_RED)
    pdf.cell(0, 8, "V I R A L   P O S T   D E C O N S T R U C T I O N", align="C", ln=1)

    # Author + date
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*C_WHITE)
    pdf.cell(0, 11, sanitize_pdf_text(d.authorName), align="C", ln=1)
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_CREAM)
    pdf.cell(0, 6, sanitize_pdf_text(d.authorHeadline), align="C", ln=1)
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(*C_MUTED)
    analyzed = datetime.fromisoformat(d.analyzedAt).strftime("%B %d, %Y")
    pdf.cell(0, 6, f"Analyzed {analyzed}", align="C", ln=1)

    pdf.ln(6)

    # Stat cards
    pdf.add_stat_card_row([
        {"label": "Likes", "value": str(d.numLikes)},
        {"label": "Comments", "value": str(d.numComments)},
        {"label": "Shares", "value": str(d.numShares)},
    ])
    pdf.ln(4)

    # Hook + CTA
    pdf.add_section_label("HOOK")
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(*C_WHITE)
    pdf.multi_cell(0, 5, sanitize_pdf_text(f'"{d.hook}"'))
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(pdf.w - pdf.l_margin - pdf.r_margin, 5, f"Type: {d.hookType}  |  Length: {d.hookLength} words", ln=1)

    pdf.ln(2)
    pdf.add_section_label("CALL TO ACTION")
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(*C_WHITE)
    cta_text = d.cta if d.cta else "No CTA detected"
    pdf.multi_cell(0, 5, sanitize_pdf_text(f'"{cta_text}"'))
    pdf.set_font("Helvetica", size=8)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(pdf.w - pdf.l_margin - pdf.r_margin, 5, f"Type: {d.ctaType}", ln=1)

    # AI section
    if d.ai:
        pdf.ln(2)
        pdf.add_section_label("WHY IT WORKED")
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_CREAM)
        pdf.multi_cell(0, 5, sanitize_pdf_text(d.ai.whyItWorked))

        pdf.ln(2)
        pdf.add_section_label("CONTENT PILLAR  /  ARCHETYPE")
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*C_WHITE)
        pdf.cell(0, 6, sanitize_pdf_text(f"{d.ai.contentPillar}  /  {d.ai.archetype}"), ln=1)

        pdf.ln(2)
        pdf.add_section_label("HOOK FORMULA")
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_ACCENT)
        pdf.multi_cell(0, 5, sanitize_pdf_text(d.ai.hookFormula))

        pdf.ln(2)
        pdf.add_section_label("CTA FORMULA")
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_ACCENT)
        pdf.multi_cell(0, 5, sanitize_pdf_text(d.ai.ctaFormula))

        pdf.ln(2)
        pdf.add_section_label("REPLICATION GUIDE")
        for step in d.ai.replicationGuide:
            pdf.set_font("Helvetica", size=9)
            pdf.set_text_color(*C_CREAM)
            pdf.multi_cell(0, 5, sanitize_pdf_text(f"  {step}"))
            pdf.ln(1)

    # Post URL
    if d.postUrl:
        pdf.ln(4)
        pdf.set_font("Helvetica", size=8)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(0, 5, sanitize_pdf_text(f"Source: {d.postUrl}"), ln=1, link=d.postUrl)

    # =========================================================
    # PAGE 2: CTA / Offer
    # =========================================================
    if include_cta:
        _add_cta_page(pdf)

    return bytes(pdf.output(dest="S"))
