from datetime import datetime
from fpdf import FPDF
from .types import FullAnalysis

# Brand colors
C_BLACK = (28, 28, 30)
C_WHITE = (240, 237, 230)
C_CREAM = (212, 207, 196)
C_RED = (192, 57, 43)
C_BORDER = (46, 46, 48)
C_MUTED = (85, 85, 85)
C_DARK_BG = (40, 40, 42)
C_POST_BG = (240, 237, 230)
C_POST_TXT = (28, 28, 30)


class ReportPDF(FPDF):
    def __init__(self):
        super().__init__(format="A4")
        self.set_auto_page_break(auto=True, margin=15)
        # Using standard fonts as fpdf defaults
        self.set_font("Helvetica", size=10)
        self._bg_color = None

    def set_background_color(self, color):
        self._bg_color = color
        # Paint current page background if already started
        if self.page_no() > 0:
            self.set_fill_color(*color)
            self.rect(0, 0, self.w, self.h, "F")

    def add_page(self, *args, **kwargs):
        super().add_page(*args, **kwargs)
        if self._bg_color:
            self.set_fill_color(*self._bg_color)
            self.rect(0, 0, self.w, self.h, "F")

    def header(self):
        pass

    def footer(self):
        if (
            self.page_no() > 1
        ):  # Skip title page footer if desired, but we'll add to all for consistency
            self.set_y(-15)
            self.set_draw_color(*C_MUTED)
            self.set_line_width(0.2)
            self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())

            self.set_y(-12)
            self.set_font("Helvetica", size=8)
            self.set_text_color(*C_MUTED)
            self.cell(0, 5, "Generated by Behram - Antifragile", 0, 0, "L")

    def add_section_label(self, label: str):
        self.ln(5)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(*C_RED)
        # letter spacing faux
        spaced_label = " ".join(label.upper())
        self.cell(0, 8, sanitize_pdf_text(spaced_label), ln=1)

    def add_section_title(self, title: str):
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(*C_WHITE)
        self.cell(0, 10, sanitize_pdf_text(title.upper()), ln=1)
        self.ln(5)

    def add_metric_row(self, label: str, value: str):
        self.set_font("Helvetica", size=10)

        # Bottom border
        start_y = self.get_y()
        self.set_draw_color(*C_BORDER)
        self.line(self.l_margin, start_y + 8, self.w - self.r_margin, start_y + 8)

        self.set_text_color(*C_CREAM)
        self.cell(100, 8, sanitize_pdf_text(label))

        self.set_text_color(*C_WHITE)
        self.cell(0, 8, sanitize_pdf_text(value), align="R", ln=1)
        self.ln(2)

    def add_stat_card_row(self, cards):
        # cards is list of dicts: {'label': str, 'value': str, 'sub': str}
        # Max 3 in a row
        width = (self.w - self.l_margin - self.r_margin - 20) / 3
        start_x = self.get_x()
        start_y = self.get_y()
        max_y = start_y

        for i, card in enumerate(cards):
            x = start_x + (i % 3) * (width + 10)
            if i > 0 and i % 3 == 0:
                start_y = max_y + 10
                x = start_x

            self.set_xy(x, start_y)
            self.set_fill_color(*C_DARK_BG)
            self.set_draw_color(*C_BORDER)

            # Draw rect
            self.rect(x, start_y, width, 25, "DF")

            # Label
            self.set_xy(x + 5, start_y + 3)
            self.set_font("Helvetica", size=8)
            self.set_text_color(180, 180, 180)  # Faded cream
            self.cell(width - 10, 5, card["label"])

            # Value
            self.set_xy(x + 5, start_y + 8)
            self.set_font("Helvetica", "B", 14)
            self.set_text_color(*C_WHITE)
            self.cell(width - 10, 8, card["value"])

            # Sub
            if "sub" in card and card["sub"]:
                self.set_xy(x + 5, start_y + 16)
                self.set_font("Helvetica", size=8)
                self.set_text_color(180, 180, 180)
                self.cell(width - 10, 5, card["sub"])

            max_y = max(max_y, start_y + 25)

        self.set_xy(self.l_margin, max_y + 5)

    def add_card(self, title: str, body: str, tag: str, tag_color=C_RED):
        self.set_fill_color(*C_DARK_BG)
        self.set_draw_color(*C_BORDER)

        start_y = self.get_y()

        # Calculate height needed
        self.set_font("Helvetica", size=9)
        safe_body = sanitize_pdf_text(body)
        num_lines = len(
            self.multi_cell(
                self.w - self.l_margin - self.r_margin - 10,
                5,
                safe_body,
                split_only=True,
            )
        )
        height = 10 + (num_lines * 5) + 10

        # Don't break across pages if possible
        if start_y + height > self.page_break_trigger:
            self.add_page()
            start_y = self.get_y()

        self.rect(
            self.l_margin, start_y, self.w - self.l_margin - self.r_margin, height, "DF"
        )

        self.set_xy(self.l_margin + 5, start_y + 5)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*C_WHITE)
        self.cell(0, 5, sanitize_pdf_text(title), ln=1)

        self.set_xy(self.l_margin + 5, self.get_y() + 2)
        self.set_font("Helvetica", size=9)
        self.set_text_color(*C_CREAM)
        self.multi_cell(0, 5, safe_body)

        self.set_xy(self.l_margin + 5, self.get_y() + 2)
        self.set_font("Helvetica", size=8)
        self.set_text_color(*tag_color)
        self.cell(0, 5, sanitize_pdf_text(tag), ln=1)

        self.ln(5)

    def add_post_card(self, text: str):
        self.set_fill_color(*C_POST_BG)

        self.set_font("Helvetica", size=9)
        safe_text = sanitize_pdf_text(text)
        num_lines = len(
            self.multi_cell(
                self.w - self.l_margin - self.r_margin - 10,
                5,
                safe_text,
                split_only=True,
            )
        )
        height = 10 + (num_lines * 5)

        start_y = self.get_y()
        if start_y + height > self.page_break_trigger:
            self.add_page()
            start_y = self.get_y()

        self.rect(
            self.l_margin, start_y, self.w - self.l_margin - self.r_margin, height, "F"
        )

        self.set_xy(self.l_margin + 5, start_y + 5)
        self.set_text_color(*C_POST_TXT)
        self.multi_cell(0, 5, safe_text)
        self.ln(5)


def truncate(text: str, length: int) -> str:
    if len(text) > length:
        return text[:length] + "..."
    return text


def sanitize_pdf_text(text: str) -> str:
    if text is None:
        return ""
    replacements = {
        "•": "-",
        "–": "-",
        "—": "-",
        "“": '"',
        "”": '"',
        "‘": "'",
        "’": "'",
        "…": "...",
        "\u00a0": " ",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    # FPDF core fonts expect Latin-1; replace unsupported chars.
    return text.encode("latin-1", "replace").decode("latin-1")


def post_title(text: str, fallback: str, length: int = 80) -> str:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    title = lines[0] if lines else fallback
    return truncate(title, length)


def add_post_list(pdf: ReportPDF, label: str, posts: list):
    pdf.add_section_label(label)
    if not posts:
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(0, 6, "No posts available.", ln=1)
        pdf.ln(2)
        return

    for i, p in enumerate(posts, 1):
        rank_hint = getattr(p, "ageAdjustedRank", 0) or getattr(p, "rank", 0) or i
        title = post_title(p.text, f"Post #{rank_hint}")
        link = getattr(p, "url", "") or ""

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*C_CREAM)
        if link:
            pdf.cell(0, 6, sanitize_pdf_text(f"{i}. {title}"), ln=1, link=link)
        else:
            pdf.cell(0, 6, sanitize_pdf_text(f"{i}. {title}"), ln=1)

        pdf.set_font("Helvetica", size=8)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(
            0,
            5,
            sanitize_pdf_text(
                f"{p.numLikes} likes • {p.numComments} comments • {p.numShares} reposts"
            ),
            ln=1,
        )
    pdf.ln(2)


def generate_pdf(a: FullAnalysis) -> bytes:
    pdf = ReportPDF()

    # Base background color for all pages
    def set_bg():
        pdf.set_background_color(C_BLACK)

    pdf.add_page()
    set_bg()

    # -------------------------------------------------------------
    # PAGE 1: TITLE
    # -------------------------------------------------------------
    pdf.set_y(pdf.h / 2 - 40)

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*C_RED)
    pdf.cell(
        0,
        10,
        "L I N K E D I N   C O M P E T I T O R   A N A L Y S I S",
        align="C",
        ln=1,
    )

    pdf.set_font("Helvetica", "B", 30)
    pdf.set_text_color(*C_WHITE)
    pdf.cell(0, 15, "[PROFILE REDACTED]", align="C", ln=1)

    pdf.set_font("Helvetica", size=12)
    pdf.set_text_color(*C_CREAM)
    pdf.cell(0, 8, "[Headline Redacted]", align="C", ln=1)

    date_str = (
        datetime.fromisoformat(a.analyzedAt.replace("Z", "+00:00")).strftime(
            "%B %d, %Y"
        )
        if a.analyzedAt
        else "Today"
    )
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_MUTED)
    pdf.cell(0, 20, sanitize_pdf_text(f"Report generated {date_str}"), align="C", ln=1)

    pdf.ln(20)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(
        0,
        10,
        sanitize_pdf_text(
            f"{a.cadence.totalPosts} posts analyzed | {a.cadence.periodStart} to {a.cadence.periodEnd}"
        ),
        align="C",
        ln=1,
    )

    # -------------------------------------------------------------
    # PAGE 2: PERFORMANCE
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.add_section_label("SECTION 1")
    pdf.add_section_title("Performance Snapshot")

    pdf.add_stat_card_row(
        [
            {
                "label": "AVG REACTIONS",
                "value": str(a.engagement.avgReactions),
                "sub": f"median: {a.engagement.medianReactions}",
            },
            {
                "label": "AVG COMMENTS",
                "value": str(a.engagement.avgComments),
                "sub": f"median: {a.engagement.medianComments}",
            },
            {
                "label": "POSTING PACE",
                "value": f"{a.cadence.postsPerWeek}/wk",
                "sub": f"every {a.cadence.avgDaysBetweenPosts} days",
            },
        ]
    )

    pdf.add_section_label("CONTENT CADENCE")
    pdf.add_metric_row("Posts Analyzed", str(a.cadence.totalPosts))
    pdf.add_metric_row(
        "Time Period", f"{a.cadence.periodStart} -> {a.cadence.periodEnd}"
    )
    pdf.add_metric_row("Weeks Covered", str(a.cadence.weeksCovered))
    pdf.add_metric_row("Total Reactions", f"{a.engagement.totalReactions:,}")
    pdf.add_metric_row("Total Comments", f"{a.engagement.totalComments:,}")

    pdf.add_section_label("POST TYPE BREAKDOWN")
    for pt in a.postTypes:
        pdf.add_metric_row(
            f"{pt.type.upper()} ({pt.percentage}%)",
            f"{pt.count} posts • avg {pt.avgReactions} reactions",
        )

    add_post_list(pdf, "TOP 5 POSTS (AGE-ADJUSTED)", a.topPosts)
    add_post_list(pdf, "BOTTOM 5 POSTS (AGE-ADJUSTED)", a.worstPosts)

    # -------------------------------------------------------------
    # PAGE 3: CONTENT STRATEGY
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.add_section_label("SECTION 2")
    pdf.add_section_title("Content Strategy")

    pdf.add_section_label("EXECUTIVE SUMMARY")
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(*C_CREAM)
    pdf.multi_cell(0, 6, sanitize_pdf_text(a.executiveSummary))

    pdf.add_section_label("CONTENT PILLARS")
    for p in a.contentPillars:
        pdf.add_card(
            p.name,
            p.description,
            f"~{p.percentageOfPosts}% of posts • {p.engagementLevel} engagement",
        )

    pdf.add_section_label("POST ARCHETYPES")
    for ar in a.postArchetypes:
        pdf.add_card(
            ar.name,
            ar.description,
            f"{ar.count} posts • {ar.engagementLevel} engagement",
        )

    # -------------------------------------------------------------
    # PAGE 4: TEXT ANALYSIS
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.add_section_label("SECTION 3")
    pdf.add_section_title("Text Analysis")

    pdf.add_section_label("TEXT PATTERNS")
    pdf.add_metric_row("Avg Word Count", str(a.textPatterns.avgWordCount))
    pdf.add_metric_row(
        "Posts with CTA", f"{a.textPatterns.postsWithCTA}/{a.cadence.totalPosts}"
    )

    lift_sign = "+" if a.textPatterns.ctaEngagementLift > 0 else ""
    pdf.add_metric_row(
        "CTA Engagement Lift", f"{lift_sign}{a.textPatterns.ctaEngagementLift}%"
    )

    pdf.add_metric_row(
        "Posts with Hook", f"{a.textPatterns.postsWithHook}/{a.cadence.totalPosts}"
    )
    pdf.add_metric_row(
        "Posts with Questions",
        f"{a.textPatterns.postsWithQuestions}/{a.cadence.totalPosts}",
    )

    pdf.add_section_label("TOP 25 WORDS (NLP FREQUENCY)")
    # Draw simple grid 2 columns
    pdf.set_font("Helvetica", size=9)
    col_w = (pdf.w - pdf.l_margin - pdf.r_margin - 10) / 2
    y_start = pdf.get_y()

    for i, w in enumerate(a.wordFrequency):
        col = 0 if i % 2 == 0 else 1
        row = i // 2

        x = pdf.l_margin + col * (col_w + 10)
        y = y_start + row * 8

        pdf.set_xy(x, y)
        pdf.set_draw_color(*C_BORDER)
        pdf.line(x, y + 6, x + col_w, y + 6)

        pdf.set_text_color(*C_CREAM)
        pdf.cell(col_w - 20, 6, f"{i+1}. {w.word}")

        pdf.set_text_color(*C_WHITE)
        pdf.cell(20, 6, str(w.count), align="R")

    pdf.set_y(pdf.get_y() + 10)

    # -------------------------------------------------------------
    # PAGE 5: BLUEPRINT
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.add_section_label("SECTION 4")
    pdf.add_section_title("Hook Blueprint")

    h = a.hookAnalysis
    pdf.add_section_label("HOOK ANALYSIS (FIRST SENTENCE)")
    pdf.add_metric_row("Avg Hook Length", f"{h.avgHookLength} words")
    pdf.add_metric_row("Urgency Rate", f"{h.urgencyRate}% of posts")

    top_hook_type = h.hookTypes[0] if h.hookTypes else None
    pdf.add_metric_row(
        "Top Hook Type",
        f"{top_hook_type.type if top_hook_type else 'N/A'} ({(top_hook_type.percentage if top_hook_type else 0)}%)",
    )
    pdf.add_metric_row(
        "Top First Words", ", ".join(w.word for w in h.topFirstWords[:5])
    )

    hs = a.hookStrategy

    pdf.add_section_label("TOP HOOK PATTERNS")
    if hs.patterns:
        for p in hs.patterns:
            pdf.add_card(p.name, p.description, f"{p.engagementLevel} engagement")
    else:
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(0, 6, "No hook patterns available.", ln=1)
        pdf.ln(2)

    pdf.add_card("WINNING HOOK FORMULA", hs.formula, "", tag_color=C_RED)

    pdf.add_section_label("TOP HOOK EXAMPLES")
    if hs.bestExamples:
        for ex in hs.bestExamples:
            pdf.add_post_card(truncate(ex.text, 220))
    else:
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(0, 6, "No hook examples available.", ln=1)
        pdf.ln(2)

    # -------------------------------------------------------------
    # PAGE 6: CTA BLUEPRINT
    # -------------------------------------------------------------
    pdf.add_page()
    pdf.add_section_label("SECTION 5")
    pdf.add_section_title("CTA Blueprint")

    cta = a.ctaAnalysis
    cs = a.ctaStrategy

    pdf.add_section_label("CTA ANALYSIS (LAST SENTENCE)")
    pdf.add_metric_row("No CTA Rate", f"{cta.noCTARate}% of posts")
    pdf.add_metric_row("Best CTA Type", cta.bestCTAType)
    pdf.add_metric_row(
        "Top Action Words", ", ".join(w.word for w in cta.topActionWords[:5])
    )

    pdf.add_card("WINNING CTA FORMULA", cs.formula, "", tag_color=C_RED)

    pdf.add_section_label("TOP CTA PATTERNS")
    if cs.patterns:
        for p in cs.patterns:
            pdf.add_card(p.name, p.description, f"{p.engagementLevel} engagement")
    else:
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(0, 6, "No CTA patterns available.", ln=1)
        pdf.ln(2)

    pdf.add_section_label("TOP CTA EXAMPLES")
    if cs.bestExamples:
        for ex in cs.bestExamples:
            pdf.add_post_card(truncate(ex.text, 220))
    else:
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*C_MUTED)
        pdf.cell(0, 6, "No CTA examples available.", ln=1)
        pdf.ln(2)

    # -------------------------------------------------------------
    # PAGE 7: OFFER
    # -------------------------------------------------------------
    pdf.add_page()

    pdf.set_y(pdf.h / 2 - 50)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(*C_RED)
    pdf.cell(0, 10, "W H A T ' S   N E X T ?", align="C", ln=1)

    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(*C_WHITE)
    pdf.cell(0, 15, "UNLOCK YOUR FULL POTENTIAL", align="C", ln=1)

    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(*C_CREAM)
    text = "Understanding your competitor's content is the first step. The next is building systems to create and distribute your own with maximum efficiency.\n\nWe're launching a Skool community for creators and entrepreneurs focused on Vibe Coding Automation — learning how to build agentic systems and AI tools just like the one that generated this report.\n\nJoin the waitlist today and get an exclusive 50% launch discount."

    # Center text body
    pdf.set_x(pdf.w / 2 - 70)
    pdf.multi_cell(140, 6, sanitize_pdf_text(text), align="C")

    pdf.ln(10)
    pdf.set_fill_color(*C_RED)
    pdf.set_text_color(*C_WHITE)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_x(pdf.w / 2 - 40)
    pdf.cell(80, 12, "JOIN THE WAITLIST ->", fill=True, align="C", ln=1)

    return bytes(pdf.output(dest="S"))
